default: all

all:
	@cd ./libjaus; make;
	@cd ./libopenJaus; make;
	@cd ./ojCmpt; make;
	@cd ./ojNodeManager; make;
	@cd ./ojVehicleSim; make;

clean:
	@cd ./libjaus; make clean;
	@cd ./libopenJaus; make clean;
	@cd ./ojCmpt; make clean;
	@cd ./ojNodeManager; make clean;
	@cd ./ojVehicleSim; make clean;

