#!/bin/sh

exec > Makefile

echo "TARGET	= 	./lib/libjaus.so"
echo "CCFLAGS	=	-Wall -std=c99 -O2 -c -g -I ./include/"

SOURCE_FILES=`find ./src/ -name "*.c"`
for cfile in $SOURCE_FILES
do
	SOURCES="$SOURCES$cfile \\\\\\n\\t\\t\\t"
	ofile=${cfile##*/}
	ofile=./Build/${ofile%c}o
	OBJECTS="$OBJECTS$ofile \\\\\\n\\t\\t\\t"
done

SOURCES=${SOURCES%" \\\\\\n"\\t\\t\\t}
echo -e "SOURCES =\t$SOURCES"

OBJECTS=${OBJECTS%" \\\\\\n"\\t\\t\\t}
echo -e "\nOBJECTS =\t$OBJECTS"

echo
echo "default : all"
echo
echo "all : \$(TARGET)"
echo
echo "clean :"
echo "	rm -f ./Build/*.o"
echo "	rm -f \$(TARGET)"
echo
echo "\$(TARGET) : \$(OBJECTS)"
echo "	gcc -shared -o \$(TARGET) \$(OBJECTS)"

for cfile in $SOURCE_FILES
do
	ofile=${cfile##*/}
	ofile=./Build/${ofile%c}o

	echo
	echo "$ofile : $cfile"
	echo "	gcc \$(CCFLAGS) -o $ofile $cfile"
done
