#! /bin/bash
# Nodemanager startup script

route add -host 224.1.0.2 eth0
route add -host 224.1.0.1 eth1

cd ..

# only need to use the main jar because it has a index which covers the other jars in lib
java -Dlog4j.configuration=file:./log4j.properties -jar lib/nodeManager.jar

