#! /bin/bash
# Nodemanager startup script

route add -host 224.1.0.2 eth0
route add -host 224.1.0.1 eth1

cd /opt/CIMAR/Core/nodeManager

java -cp /usr/include/cimar/jaus.jar:bin/nodeManager.jar NodeManager

