#! /bin/bash 
# CIMAR Core Software Install Script

# JAVA Library and Node Manager
cd ./libjausJava; ./Install; cd ..;
cd ./nodeManager; ./Install; cd ..;

# C Libraries
cd ./libcimar; ./Install-CIMAR.sh; cd ..;
cd ./libjausC; ./Install-CIMAR.sh; cd ..;
cd ./libnodeManager; ./Install-CIMAR.sh; cd ..;

echo ;
echo CIMAR Core Software Install Complete
echo ;
