# ./src/message/inform/platform

INC		=	include
SRC		=	
BUILD	=	Build/
CC		=	gcc
CCFLAGS	=	-Wall -O2 -fPIC -g -c 

OBJECTS =	\
			$(DIRPATH)$(BUILD)reportPlatformSpecificationsMessage.o \
			$(DIRPATH)$(BUILD)reportPlatformOperationalDataMessage.o \
			$(DIRPATH)$(BUILD)reportGlobalPoseMessage.o \
			$(DIRPATH)$(BUILD)reportVelocityStateMessage.o \
			$(DIRPATH)$(BUILD)reportWrenchEffortMessage.o \
			$(DIRPATH)$(BUILD)reportDiscreteDevicesMessage.o \
			$(DIRPATH)$(BUILD)reportGlobalVectorMessage.o \
			$(DIRPATH)$(BUILD)reportTravelSpeedMessage.o \
			$(DIRPATH)$(BUILD)reportWaypointCountMessage.o \
			$(DIRPATH)$(BUILD)reportGlobalWaypointMessage.o \

all: $(OBJECTS)

$(DIRPATH)$(BUILD)reportPlatformSpecificationsMessage.o : $(SRC)reportPlatformSpecificationsMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportPlatformSpecificationsMessage.o ./reportPlatformSpecificationsMessage.c	

$(DIRPATH)$(BUILD)reportPlatformOperationalDataMessage.o : $(SRC)reportPlatformOperationalDataMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportPlatformOperationalDataMessage.o ./reportPlatformOperationalDataMessage.c	

$(DIRPATH)$(BUILD)reportGlobalPoseMessage.o : $(SRC)reportGlobalPoseMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportGlobalPoseMessage.o ./reportGlobalPoseMessage.c	

$(DIRPATH)$(BUILD)reportVelocityStateMessage.o : $(SRC)reportVelocityStateMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportVelocityStateMessage.o ./reportVelocityStateMessage.c	

$(DIRPATH)$(BUILD)reportWrenchEffortMessage.o : $(SRC)reportWrenchEffortMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportWrenchEffortMessage.o ./reportWrenchEffortMessage.c	

$(DIRPATH)$(BUILD)reportDiscreteDevicesMessage.o : $(SRC)reportDiscreteDevicesMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportDiscreteDevicesMessage.o ./reportDiscreteDevicesMessage.c	

$(DIRPATH)$(BUILD)reportGlobalVectorMessage.o : $(SRC)reportGlobalVectorMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportGlobalVectorMessage.o ./reportGlobalVectorMessage.c	

$(DIRPATH)$(BUILD)reportTravelSpeedMessage.o : $(SRC)reportTravelSpeedMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportTravelSpeedMessage.o ./reportTravelSpeedMessage.c	

$(DIRPATH)$(BUILD)reportWaypointCountMessage.o : $(SRC)reportWaypointCountMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportWaypointCountMessage.o ./reportWaypointCountMessage.c	

$(DIRPATH)$(BUILD)reportGlobalWaypointMessage.o : $(SRC)reportGlobalWaypointMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)reportGlobalWaypointMessage.o ./reportGlobalWaypointMessage.c	



$(DIRPATH)$(BUILD)jausMessage.o : $(SRC)jausMessage.c 
	$(CC) $(CCFLAGS) -I $(DIRPATH)$(INC) -o $(DIRPATH)$(BUILD)jausMessage.o ./jausMessage.c	