#!/bin/sh

exec > Makefile

OPEN_JAUS_HOME=../OpenJAUSv3.3

echo "TARGET	= 	./messageTest"
echo "CCFLAGS	=	-Wall -fPIC -fno-strict-aliasing -O2 -c -g -I ./include/ -I $OPEN_JAUS_HOME/libjaus/include/"
echo "LFLAGS	=	-L $OPEN_JAUS_HOME/libjaus/lib/"
echo "LIBS		=	-ljaus -lrt"

SOURCE_C_FILES=`find ./ -name "*.c"`
for cfile in $SOURCE_C_FILES
do
	SOURCES="$SOURCES$cfile \\\\\\n\\t\\t"
	ofile=${cfile##*/}
	ofile=./Build/${ofile%c}o
	OBJECTS="$OBJECTS$ofile \\\\\\n\\t\\t"
done

SOURCES=${SOURCES%" \\\\\\n"\\t\\t}
echo -e "SOURCES =\t$SOURCES"

OBJECTS=${OBJECTS%" \\\\\\n"\\t\\t}
echo -e "\nOBJECTS =\t$OBJECTS"

echo
echo "default : all"
echo
echo "all : \$(TARGET)"
echo
echo "clean :"
echo "	rm -f ./Build/*.o"
echo "	rm -f \$(TARGET)"
echo
echo "\$(TARGET) : \$(OBJECTS)"
echo "	gcc \$(LFLAGS) -o \$(TARGET) \$(OBJECTS) \$(LIBS)"

for cfile in $SOURCE_C_FILES
do
	ofile=${cfile##*/}
	ofile=./Build/${ofile%c}o

	echo
	echo "$ofile : $cfile"
	echo "	gcc \$(CCFLAGS) -o $ofile $cfile"
done
