#!/bin/sh

exec > messageTest.c

SOURCE_C_FILES=`find ../OpenJAUSv3.3/libjaus/src/ -name "*.c" | grep /message/`
for cfile in $SOURCE_C_FILES
do
	ofile=${cfile##*/}
	ofile=${ofile%.c}
	MESSAGES="$MESSAGES$ofile\n"
done

echo -e "#include <stdio.h>"
echo -e "#include <jaus.h>\n\n"
echo "int main(void)"
echo "{"

for message in `echo -e $MESSAGES`
do
	msgType=`expr substr $message 1 1 | tr [:lower:] [:upper:]`
	echo -e "\t$msgType${message:1} $message;"
done

echo -e "\n"

for message in `echo -e $MESSAGES`
do
	msgType=`expr substr $message 1 1 | tr [:lower:] [:upper:]`
	msgType="$msgType${message:1}"

	echo -e "\t$message = ${message:0}Create();"
	echo -e "\tjausMessage = ${message:0}ToJausMessage($message);"
	echo -e "\t${message:0}Destroy($message);"
	echo -e "\tif(jausMessage->dataSize == 0)"
	echo -e "\t{"
	echo -e "\t\tprintf(\"${message:0}ToJausMessage failed\\\n\");"
	echo -e "\t}"
	echo -e "\telse"
	echo -e "\t{"
	echo -e "\t\t$message = ${message:0}FromJausMessage(jausMessage);"
	echo -e "\t\tif($message == NULL)"
	echo -e "\t\t{"
	echo -e "\t\t\tprintf(\"${message:0}FromJausMessage failed\\\n\");"
	echo -e "\t\t}"
	echo -e "\t\telse"
	echo -e "\t\t{"
	echo -e "\t\t\t${message:0}Destroy($message);"
	echo -e "\t\t}"
	echo -e "\t}"
	echo -e "\tjausMessageDestroy(jausMessage);"
	echo
done

echo -e "\treturn 0;"
echo "}"
