#!/bin/sh

exec > Makefile

OPEN_JAUS_HOME=$HOME/OpenJAUSv3.2

echo "EXE		= 	./bin/nodeManager"
echo "TARGET	= 	./lib/libopenJAUS.so"
echo "CCFLAGS	=	-Wall -fno-strict-aliasing -O2 -c -g -I ./include/ -I $OPEN_JAUS_HOME/libjaus/include/"
echo "LFLAGS	=	-L $OPEN_JAUS_HOME/libjaus/lib/"
echo "LIBS		=	-ljaus -lrt"

SOURCE_C_FILES=`find ./src/ -name "*.c"`
for cfile in $SOURCE_C_FILES
do
	SOURCES="$SOURCES$cfile \\\\\\n\\t\\t"
	ofile=${cfile##*/}
	ofile=./Build/${ofile%c}o
	OBJECTS="$OBJECTS$ofile \\\\\\n\\t\\t"
done

SOURCE_CPP_FILES=`find ./src/ -name "*.cpp"`
for cfile in $SOURCE_CPP_FILES
do
	SOURCES="$SOURCES$cfile \\\\\\n\\t\\t"
	ofile=${cfile##*/}
	ofile=./Build/${ofile%cpp}o
	if [ "$ofile" != "./Build/main.o" ]; then
		OBJECTS="$OBJECTS$ofile \\\\\\n\\t\\t"
	fi
done

SOURCES=${SOURCES%" \\\\\\n"\\t\\t}
echo -e "SOURCES =\t$SOURCES"

OBJECTS=${OBJECTS%" \\\\\\n"\\t\\t}
echo -e "\nOBJECTS =\t$OBJECTS"

echo
echo "default : all"
echo
echo "all : \$(EXE)"
echo
echo "clean :"
echo "	rm -f ./Build/*.o"
echo "	rm -f \$(TARGET)"
echo "	rm -f \$(EXE)"
echo
echo "\$(TARGET) : \$(OBJECTS)"
echo "	g++ -shared \$(LFLAGS) -o \$(TARGET) \$(OBJECTS) \$(LIBS)"
echo
echo "\$(EXE) : \$(TARGET) ./Build/main.o"
echo "	g++ \$(LFLAGS) -o \$(EXE) ./Build/main.o \$(LIBS) \$(TARGET)"

for cfile in $SOURCE_C_FILES
do
	ofile=${cfile##*/}
	ofile=./Build/${ofile%c}o

	echo
	echo "$ofile : $cfile"
	echo "	gcc \$(CCFLAGS) -o $ofile $cfile"
done

for cfile in $SOURCE_CPP_FILES
do
	ofile=${cfile##*/}
	ofile=./Build/${ofile%cpp}o

	echo
	echo "$ofile : $cfile"
	echo "	g++ \$(CCFLAGS) -o $ofile $cfile"
done
