#! /bin/bash
# CIMAR library Uninstall Script

echo ;
echo CIMAR Library Uninstall Begin
echo ;

if [ "$OPENJAUS_HOME" = "" ]; then
    echo OPENJAUS_HOME not set...  Using /usr
    echo ;
    OPENJAUS_HOME=/usr
fi

rm -fv $OPENJAUS_HOME/include/cimar.h
rm -rfv $OPENJAUS_HOME/include/cimar/utm
rm -fv $OPENJAUS_HOME/include/cimar/bres.h
rm -fv $OPENJAUS_HOME/include/cimar/datagramPacket.h
rm -fv $OPENJAUS_HOME/include/cimar/datagramSocket.h
rm -fv $OPENJAUS_HOME/include/cimar/greatCircle.h
rm -fv $OPENJAUS_HOME/include/cimar/gridMapLib.h
rm -fv $OPENJAUS_HOME/include/cimar/inetAddress.h
rm -fv $OPENJAUS_HOME/include/cimar/logLib.h
rm -fv $OPENJAUS_HOME/include/cimar/multicastSocket.h
rm -fv $OPENJAUS_HOME/include/cimar/networkInterface.h
rm -fv $OPENJAUS_HOME/include/cimar/pointGg.h
rm -fv $OPENJAUS_HOME/include/cimar/pointLla.h
rm -fv $OPENJAUS_HOME/include/cimar/pointUtm.h
rm -fv $OPENJAUS_HOME/include/cimar/portLib.h
rm -fv $OPENJAUS_HOME/include/cimar/properties.h
rm -fv $OPENJAUS_HOME/include/cimar/queue.h
rm -fv $OPENJAUS_HOME/include/cimar/timeLib.h
rm -fv $OPENJAUS_HOME/include/cimar/torusBuffer.h
rm -fv $OPENJAUS_HOME/include/cimar/vector.h

rm -fv $OPENJAUS_HOME/lib/libcimar.*

echo ;
echo CIMAR Library Uninstall Complete
echo ;
