#!/bin/sh

exec > messageTest.c

SOURCE_C_FILES=`find ./src/ -name "*.c" | grep /message/`
for cfile in $SOURCE_C_FILES
do
	ofile=${cfile##*/}
	ofile=${ofile%.c}
	MESSAGES="$MESSAGES$ofile\n"
done

echo -e "#include <jaus.h>\n\n\n\n"
echo "void main(void)"
echo "{"

for message in `echo -e $MESSAGES`
do
	msgType=`expr substr $message 1 1 | tr [:lower:] [:upper:]`
	echo -e "\t$msgType${message:1} $message;"
done

echo -e "\n\n"

for message in `echo -e $MESSAGES`
do
	msgType=`expr substr $message 1 1 | tr [:lower:] [:upper:]`
	msgType="$msgType${message:1}"

	echo -e "\t$message = ${message:0}Create();"
	echo -e "\tjausMessage = ${message:0}ToJausMessage($message);"
	echo -e "\t$message = ${message:0}FromJausMessage(jausMessage);"
	echo -e "\tjausMessageDestroy(jausMessage);"
	echo
done

echo "}"
